### ISSUE TITLE
sh: 1: tailf: not found

### ISSUE THREAD

**Issue by arshdkhn1** [JanitorTechnology/janitor#229]
**OS:** Lubuntu 17.10

When I run `npm run watch` I get the below error -

```

arshad@anonymous:~/Documents/gitrepos/janitor$ npm run watch

> janitor.technology@0.0.9 prewatch /home/arshad/Documents/gitrepos/janitor
> touch janitor.log && chmod 600 janitor.log


> janitor.technology@0.0.9 watch /home/arshad/Documents/gitrepos/janitor
> watch-run --initial --pattern 'app.js,package.json,api/**,lib/**,templates/**' --stop-on-error npm run app & tailf janitor.log -n 0

sh: 1: tailf: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! janitor.technology@0.0.9 watch: `watch-run --initial --pattern 'app.js,package.json,api/**,lib/**,templates/**' --stop-on-error npm run app & tailf janitor.log -n 0`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the janitor.technology@0.0.9 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arshad/.npm/_logs/2018-01-14T18_16_18_204Z-debug.log
```

**/home/arshad/.npm/_logs/2018-01-14T18_16_18_204Z-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/arshad/.nvm/versions/node/v9.4.0/bin/node',
1 verbose cli   '/home/arshad/.nvm/versions/node/v9.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle janitor.technology@0.0.9~prewatch: janitor.technology@0.0.9
6 verbose lifecycle janitor.technology@0.0.9~prewatch: unsafe-perm in lifecycle true
7 verbose lifecycle janitor.technology@0.0.9~prewatch: PATH: /home/arshad/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/arshad/Documents/gitrepos/janitor/node_modules/.bin:/home/arshad/.nvm/versions/node/v9.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
8 verbose lifecycle janitor.technology@0.0.9~prewatch: CWD: /home/arshad/Documents/gitrepos/janitor
9 silly lifecycle janitor.technology@0.0.9~prewatch: Args: [ '-c', 'touch janitor.log && chmod 600 janitor.log' ]
10 silly lifecycle janitor.technology@0.0.9~prewatch: Returned: code: 0  signal: null
11 info lifecycle janitor.technology@0.0.9~watch: janitor.technology@0.0.9
12 verbose lifecycle janitor.technology@0.0.9~watch: unsafe-perm in lifecycle true
13 verbose lifecycle janitor.technology@0.0.9~watch: PATH: /home/arshad/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/arshad/Documents/gitrepos/janitor/node_modules/.bin:/home/arshad/.nvm/versions/node/v9.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
14 verbose lifecycle janitor.technology@0.0.9~watch: CWD: /home/arshad/Documents/gitrepos/janitor
15 silly lifecycle janitor.technology@0.0.9~watch: Args: [ '-c',
15 silly lifecycle   'watch-run --initial --pattern \'app.js,package.json,api/**,lib/**,templates/**\' --stop-on-error npm run app & tailf janitor.log -n 0' ]
16 info lifecycle janitor.technology@0.0.9~watch: Failed to exec watch script
17 verbose stack Error: janitor.technology@0.0.9 watch: `watch-run --initial --pattern 'app.js,package.json,api/**,lib/**,templates/**' --stop-on-error npm run app & tailf janitor.log -n 0`
17 verbose stack spawn ENOENT
17 verbose stack     at ChildProcess.<anonymous> (/home/arshad/.nvm/versions/node/v9.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
17 verbose stack     at ChildProcess.emit (events.js:160:13)
17 verbose stack     at maybeClose (internal/child_process.js:943:16)
17 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
18 verbose pkgid janitor.technology@0.0.9
19 verbose cwd /home/arshad/Documents/gitrepos/janitor
20 verbose Linux 4.13.0-25-generic
21 verbose argv "/home/arshad/.nvm/versions/node/v9.4.0/bin/node" "/home/arshad/.nvm/versions/node/v9.4.0/bin/npm" "run" "watch"
22 verbose node v9.4.0
23 verbose npm  v5.6.0
24 error file sh
25 error code ELIFECYCLE
26 error errno ENOENT
27 error syscall spawn
28 error janitor.technology@0.0.9 watch: `watch-run --initial --pattern 'app.js,package.json,api/**,lib/**,templates/**' --stop-on-error npm run app & tailf janitor.log -n 0`
28 error spawn ENOENT
29 error Failed at the janitor.technology@0.0.9 watch script.
29 error This is probably not a problem with npm. There is likely additional logging output above.
30 verbose exit [ 1, true ]
```

**Comment by jankeromnes** [comment]
Thanks for reporting this bug! I think you can fix this issue by running `sudo apt-get install tailf`.

**Comment by arshdkhn1** [comment]
@jankeromnes no tailf for lubuntu. https://packages.ubuntu.com/search?keywords=tailf&searchon=names&exact=1&suite=artful&section=all

**Comment by arshdkhn1** [comment]
https://packages.ubuntu.com/search?suite=all&arch=any&exact=1&searchon=names&keywords=tailf

**Comment by arshdkhn1** [comment]
https://github.com/JanitorTechnology/janitor/pull/230

**Comment by tnguyenns1** [comment]
tailf [is deprecated](http://manpages.ubuntu.com/manpages/xenial/en/man1/tailf.1.html), fwiw
