### ISSUE TITLE
Adding projects on db.json generate errors

### ISSUE THREAD

**Issue by Mte90** [JanitorTechnology/janitor#289]
```[2018-02-28T15:51:56.938Z] [fail] session evalmachine.<anonymous>:175
                  const projectUpdatedFuzzy = project.data.updated
                                                           ^
 
TypeError: Cannot read property 'updated' of undefined
    at evalmachine.<anonymous>:175:60
    at Script.runInContext (vm.js:74:29)
    at Script.runInNewContext (vm.js:80:15)
    at runner (/var/www/janitor/node_modules/fleau/fleau.js:247:12)
    at /var/www/janitor/node_modules/camp/lib/camp.js:88:16
    at Array.map (<anonymous>)
    at ServerResponse.res.template (/var/www/janitor/node_modules/camp/lib/camp.js:84:37)
    at Object.exports.landingPage (/var/www/janitor/lib/routes.js:104:12)
    at app.route (/var/www/janitor/app.js:91:12)
    at gotQueries (/var/www/janitor/node_modules/camp/lib/camp.js:910:7)
(node:1003) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'updated' of undefined
(node:1003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)```

With this on db.json: ```"projects": {
   "firefox": {},
    "chromium": {}
  },```
I get this error and the website is not running.

**Comment by jankeromnes** [comment]
Thanks for reporting this issue!

The problem comes from the fact that you're trying to hack projects manually into `db.json`, but they don't have the [correct format](https://github.com/JanitorTechnology/janitor/blob/f5d473c7eda768b340f42e0b76525425f8efb6b6/lib/machines.js#L447-L471) expected by the server. (More details on `db.json`'s various entries and expected formats can be found [here](https://discourse.janitor.technology/t/explaining-db-json/12)).

The safest way to add a project to a Janitor instance is to sign in as an admin user (that user's email should be in the `"admins"` key `db.json`, like so `"admins": { "user@example.com": true }`), and then navigate to the URL `/admin/projects/`. At the bottom of the page, you'll see a form to add a new project (you have to provide a project ID e.g. `project`, a name e.g. `Project`, and optionally an icon e.g. `/img/janitor.svg`).

**Comment by Mte90** [comment]
Maybe add a check in the db.js library is the most simple way to avoid other tickets in the future like that

**Comment by jankeromnes** [comment]
> Maybe add a check in the db.js library is the most simple way to avoid other tickets in the future like that

Great suggestion, thanks! 😄 

Or, better documentation on how to add data to a development instance of Janitor.

Our longer term objective is to make Janitor really self-service, so that you could add new Docker servers and projects to a Janitor instance without being an admin, simply by clicking through an intuitive UI (e.g. we'd like to be a bit like Airbnb, where it's super easy for anyone to rent or to provide appartments. We'd like to do the same for OSS dev environments).
